app/aws7/urls.py
from django.contrib import admin
from django.urls import include, path

from aws7 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('sobrecarga/', views.sobrecarga, name='sobrecarga'),
    path('tareas/', include('tareas.urls'))
]

app/tareas/urls.py
from django.urls import path

from tareas import views

app_name = 'tareas'
urlpatterns = [
    path('', views.tareas, name='tareas'),
    path('agregar/', views.agregar, name='agregar'),
    path('<int:id>/eliminar', views.eliminar, name='eliminar'),
    path('<int:id>/actualizar', views.actualizar, name='actualizar')
]

app/tareas/models.py
from django.db import models


class Tarea(models.Model):
    id = models.AutoField(primary_key=True)
    texto = models.CharField(max_length=50)
    prioridad = models.IntegerField()

    def __str__(self):
        return f'{self.texto}'

    class Meta:
        ordering = ['prioridad', 'texto']

app/tareas/forms.py
from django import forms
from tareas.models import Tarea


class TareaFormulario(forms.ModelForm):
    class Meta:
        model = Tarea
        fields = '__all__'
        widgets = {
            'prioridad': forms.NumberInput(attrs={'class': 'form-control'}),
            'texto': forms.TextInput(attrs={'class': 'form-control'}),
        }

app/aws7/views.py
import math

from django.http import HttpRequest
from django.shortcuts import render


def index(request: HttpRequest):
    return render(request, 'index.html')


def sobrecarga(request: HttpRequest):
    sum = 0
    for i in range(10**7):
        sum += math.sqrt(i) * math.sin(i) * math.cbrt(i)
    return render(request, 'sobrecarga.html')

app/tareas/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpRequest
from django.shortcuts import redirect, render
from django.urls import reverse

from tareas.forms import TareaFormulario
from tareas.models import Tarea


def tareas(request: HttpRequest):
    tareas = Tarea.objects.all()
    return render(request, 'tareas/tareas.html', {
        'tareas': tareas
    })

def agregar(request: HttpRequest):
    if request.method == 'POST':
        formulario = TareaFormulario(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect(reverse('tareas:tareas'))
        else:
            return render(request, 'tareas/agregar.html', {
                'formulario': formulario,
                'accion': 'Agregar'
            })
    return render(request, 'tareas/agregar.html', {
        'formulario': TareaFormulario(),
        'accion': 'Agregar'
    })

def actualizar(request: HttpRequest, id):
    try:
        tarea = Tarea.objects.get(pk=id)
        formulario = TareaFormulario(instance=tarea)
    except ObjectDoesNotExist:
        return redirect(reverse('tareas:tareas'))
    if request.method == 'POST':
        formulario = TareaFormulario(request.POST, instance=tarea)
        if formulario.is_valid():
            formulario.save()
            return redirect(reverse('tareas:tareas'))
        else:
            return render(request, 'tareas/agregar.html', {
                'formulario': formulario,
                'accion': 'Actualizar'
            })
    return render(request, 'tareas/agregar.html', {
        'formulario': formulario,
        'accion': 'Actualizar'
    })

def eliminar(_, id):
    try:
        tarea = Tarea.objects.get(pk=id)
    except ObjectDoesNotExist:
        return redirect(reverse('tareas:tareas'))
    tarea.delete()
    return redirect(reverse('tareas:tareas'))

app/aws7/templates/index.html
{% extends 'plantilla.html' %}

{% block titulo %}Mini Blog{% endblock %}

{% block contenido %}
<h1>Mini Blog</h1>
<p>
    Se supone que aquí debería haber una aplicación web para gestionar los productos de un supermercado y otras
    tareas. Sin embargo eso era un caso ficticio, además que no es lo importante de esta evaluación, sino que se
    note que somos capaces de implementar alguna aplicación web en la nube usando una variedad de servicios de aws.
    Es por ello que decidí escribir este mini blog detallando cómo fue el proceso que seguí para subir una
    aplicación a aws. También hice mini aplicación para gestionar tareas, para poder comprobar la conexión con una
    base de datos.
</p>
<p>
    Lo primero que tuve que hacer para poder subir una aplicación web a aws, fue crear una aplicación web. Como la
    parte de la programación no es lo importante de esta evaluación me ahorraré los detalles. Pero si alguien quiere
    revisar, aquí está todo el código de la aplicación <a href="https://github.com/pinguin-frosch/aws7">aws7</a>.
</p>
<p>
    Necesito principalmente 3 servicios de aws, ec2, rds y vpc. Voy a empezar con la vpc. Tengo que crear una vpc
    con 4 subredes, dos públicas y dos privadas. Tienen que ser 2 de cada una porque esos requisitos pide rds con
    mysql, quizás otros motores de base de datos no sean tan exigentes. Usaré la dirección de base que ofrece amazon
    para la vpc, es decir, 10.10.10.0/16. Para las 4 subredes también voy a usar las redes por defecto, no hace
    falta cambiar nada de eso en el proyecto que yo realice.
</p>
<p>
    A continuación lo que hice fue crear la base de datos con rds. No es nada complicado de hacer. La mayoría de las
    configuraciones las dejé por defecto. Traté de usar las opciones más básicas, ya que no necesito más, además así
    me ahorro problemas de tener que calcular los costos y saber si me va a alcanzar para el ejercicio. Me aseguré
    de que la base de datos quedara en una de las subredes privadas.
</p>
<p>
    Tarda un momento en crearse la base de datos, y ahora hay otro problema. Como está en una subred privada, la
    única forma de conectarse a la base de datos es a través de un computador que sea parte de la vpc. Y no tengo
    ninguno, así que de momento no puedo hacer ninguna configuración en la base de datos, porque me falta crear la
    base de datos para la aplicación web y un usuario no privilegiado para manejar esa base de datos.
</p>
<p>
    Ahora me dirigí a ec2 y creé un nuevo servidor. Usé amazon linux, ya que es una de las opciones de la capa
    gratuita de amazon para ec2. Usé el par de claves vockey, ya que las instancias de ec2 lo tienen por defecto y
    así me puedo conectar después desde mi computador, solo tengo que descargar el archivo de credencial desde aws
    academy. Sino tendría que generar claves pares con mi computador y el servidor y copiar la clave pública de mi
    computador al servidor antes de poder conectarme.
</p>
<p>
    También agregué el servidor a la parte pública de la vpc y configuré un grupo de seguridad que permite
    conexiones de tipo ssh y http. En cuanto al espacio usé los 30gb máximos que permite aws en la capa gratuita.
</p>
<p>
    Luego descargué la credencial para poder conectarme al servidor y administrarlo. Me conecté mediante ssh. Es
    necesario cambiarle los permisos al archivo porque por defecto son muy permisivos y ssh los rechaza, así que
    tuve que usar 400 para que funcione.
</p>
<p>
    Una vez en el servidor, lo primero que tuve que hacer fue instalar los programas necesarios. Como hice la
    aplicación con Docker no necesito casi nada, solo tuve que instalar docker, docker compose y git en el servidor.
    Como estaba usando amazon linux usé estos comandos para hacerlo:
</p>
<ul class="text-break">
    <li>sudo yum install -y docker git</li>
    <li>sudo usermod -aG docker $USER</li>
    <li>sudo systemctl enable --now docker</li>
    <li>sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname
        -s)-$(uname-m) -o /usr/local/bin/docker-compose</li>
    <li>sudo chmod +x /usr/local/bin/docker-compose</li>
</ul>
<p>
    Luego tuve que reiniciar el servidor para aplicar los permisos de grupos de linux, ya que sino el usuario
    ec2-user no puede usar docker para construir las imágenes y contenedores.
</p>
<p>
    Una vez todo eso terminado, solo tuve que clonar el código de la aplicación desde github. Modificar el archivo
    de configuración de la aplicación. Y luego construir las imágenes para correr los contenedores con esos datos.
    Dentro de los contenedores que estoy usando hay uno de mysql, así que con esta aplicación voy a conectarme a la
    base de datos que está en rds para configurar la base de datos.
</p>
<p>
    Es importante mencionar que la base de datos usa una dirección ip que no podemos ver desde la interfaz de aws.
    Al menos no la encontré yo. Pero si nos ofrece una dirección dns, y esa debemos usar, por eso es importante que
    los computadores estén en la misma red, porque cada red tiene un servicio de dns que resuelve las entradas
    locales.
</p>
<p>
    Una vez dentro de la base de datos agregué el usuario y la base de datos que necesitaba para la aplicación web.
    Eso se hace con los comandos apropiados de mysql. Son súper simples, solo usé estos:
</p>
<ul>
    <li>create user 'aws7'@'%' identified by 'password';</li>
    <li>grant all on aws7.* to 'aws7'@'%';</li>
</ul>
<p>
    Cuando ya tenía eso, me aseguré de que pudiera conectarse a la base de datos con ese usuario. Y después usé las
    mismas credenciales en la aplicación y la ejecuté. Pero no funcionó, al menos el servidor web funciona porque me
    dió un error 500. Siempre se me olvida que en Django hay que realizar las migraciones para que la base de datos
    tenga las tablas necesarias antes de funcionar. Así que entré al contenedor con docker exec -it e hice
    justamente eso.
</p>
<p>
    Ahora sí estaba funcionando, lo primero que hice fue agregar algunas tareas para comprobar la conexión
    nuevamente ya desde la aplicación. Originalmente solo hice una aplicación de tareas para tener algo que guardar
    en la base de datos. Pero después agregué esta especie de blog para que no quedara tan pobre. Si tengo tiempo
    después quizás agregue usuarios para que cada persona pueda tener su propia lista de tareas.
</p>
<hr>
<p>
    Después de unas horas decidí volver a visitar la página y me dí cuenta que ya no funcionaba la aplicación. Entré a
    awsacademy y me puse a leer las instrucciones que aparecián al lado. En cuanto a ec2 dice que las instancias se van
    a apagar cuando uno cierre la sesión, así que cuando uno las vuelva a enceder van a cambiar las direcciones ip.
    Logré solucionar eso con una dirección ip elástica, pero sigue estando el problema de que el servidor se va a apagar
    en máximo 4 horas. Pero no puedo hacer nada respecto a eso, ya que esas son condiciones del laboratorio.
</p>
<p>
    También decidí explorar algunas cosas más en aws y configuré amazon cloudwatch. Lo configure de modo que si por
    alguna razón la instancia ec2 del servidor no está disponible, la reinicie automáticamente. Así uno no tiene que
    estar pendiente todo el tiempo del servidor, a menos que sean cosas críticas. Finalmente lo último que hice fue
    configuras algunas reglas en las acl de la vpc. Bloquié todas las conexiones entrantes de tipo icmp, por lo que
    ninguna instancia de la vpc va a responder a un ping. Para demostrar que las reglas funcionan a nivel vpc, agregué
    una regla de seguridad a la instancia del servidor web que permite todo tráfico icmp y aún así no puedo enviar
    ningún ping, pero si quito la regla de la acl funciona de inmediato.
</p>
<hr>
<p>
    Logré encontrar una solución para poder compartir la cuenta de aws. No puedo acceder a las credenciales de la
    cuenta, pero lo que sí puedo hacer es copiar el enlace de inicio de sesión que se genera cuando uno pulsa el botón
    de aws. Solo es válido durante unos 20 minutos, así que quien lo reciba debe abrir el enlace de inmediato, luego no
    hay que preocuparse porque la sesión permanecerá abierta.
</p>
<hr>
<p>
    Ahora como parte de la última evaluación tenemos que hacer otras cosas extra. Más que nada hay que agregar servicios
    de modo que las instancias en ejecución se adapten al tráfico por parte de los usuarios. Para ello hay varias cosas
    que se pueden hacer en aws. Necesitamos un grupo de destino, plantilla de ami, balanceadores de carga, grupos de auto
    scaling, etc.
</p>
<p>
    Lo primero que tengo que hacer es crear una imagen de ami a partir de la instancia actual en la que estoy ejecutando el
    servidor. Así tengo una copia del servidor tal como está actualmente y eso lo puedo usar después para crear más copias
    cuando lo necesite. Precisamente voy a usar la ami para crear una plantilla de lanzamiento. Es lo que me permite crear
    instancias con una configuración predeterminada, además de usar la ami que yo quiera.
</p>
<p>
    Una vez con todo eso configurado, es hora de crear un grupo de destino. Como aún no hemos configurado un balanceador de
    carga solo tenemos que crearlo con la configuración por defecto, asegurándonos de que actualizamos las configuraciones
    de red apropiadamente. Ahora creamos un balanceador de carga. Solo tenemos nuevamente que verificar la configuración de
    red y asignar el grupo de destino, para que diriga las peticiones al grupo y luego a alguna instancia particular.
</p>
<p>
    Finalmente hay que crear un grupo de auto scaling de ec2. Aquí son más pasos los que hay que realizar. Ya que hay que
    conectarlo con el grupo de destino, configurar las redes. Los parámetros de autoescalado, etc. Pero siguiendo el wizard
    paso a paso no debería haber ningún problema solo con leer. Y con eso ya tenemos las instancias ejecutándose al nivel
    que necesiten los usuarios. El grupo de autoescalado se encargará de expandir o contraer según sea necesario.
</p>
{% endblock %}

app/aws7/templates/plantilla.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block titulo %}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">AWS7</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbar">
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'index' %}">Blog</a>
                    <a class="nav-link" href="{% url 'tareas:tareas' %}">Tareas</a>
                    <a class="nav-link" href="{% url 'sobrecarga' %}">Sobrecarga</a>
                </div>
            </div>
        </div>
    </nav>
    <div class="container mt-2">
        {% block contenido %}{% endblock %}
    </div>
</body>

</html>

app/aws7/templates/sobrecarga.html
{% extends 'plantilla.html' %}

{% block titulo %}Mini Blog{% endblock %}

{% block contenido %}
<h1>Página para sobrecargar la CPU</h1>
<p>Se recargará la página en algunos segundos</p>
<script>
    setTimeout(function () {
        window.location.reload()
    }, 1000)
</script>
{% endblock %}

app/tareas/templates/tareas/agregar.html
{% extends 'plantilla.html' %}

{% block titulo %}{{ accion }} tarea{% endblock %}

{% block contenido %}
<h1>{{ accion }} tarea</h1>
<a href="{% url 'tareas:tareas' %}">Ver tareas</a>
<form method="post">
    {% csrf_token %}
    {{ formulario.as_p }}
    <input type="submit" value="Enviar" class="btn btn-primary">
</form>
{% endblock %}

app/tareas/templates/tareas/tareas.html
{% extends 'plantilla.html' %}

{% block titulo %}Lista de tareas{% endblock %}

{% block contenido %}

<h1>Lista de tareas</h1>
<a href="{% url 'tareas:agregar' %}">Agregar tarea</a>

{% if tareas %}
<table class="table table-bordered mt-3">
    <thead>
        <tr>
            <th>Prioridad</th>
            <th>Texto</th>
            <th>Actualizar</th>
            <th>Eliminar</th>
        </tr>
    </thead>
    <tbody>
        {% for tarea in tareas %}
        <tr>
            <td>{{ tarea.prioridad }}</td>
            <td>{{ tarea.texto }}</td>
            <td>
                <a href="{% url 'tareas:actualizar' tarea.id %}" class="btn btn-sm btn-success">⟳</a>
            </td>
            <td>
                <a href="{% url 'tareas:eliminar' tarea.id %}" class="btn btn-sm btn-danger">⌫</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}

{% endblock %}